### ISSUE TITLE
Toponym citations

### ISSUE THREAD

**Issue by docuracy** [docuracy/Locolligo#5]
LP standard requires the `names` property and at least the first of the `toponyms` to have a `citation`, and for at least one `citation` to have a year (implemented as a `when`).

PROPOSAL: Drop the _requirements_, because they bloat the datasets and are not pertinent to non-place feature types.

**Comment by rsimon** [comment]
+1! I think its the same case like [this](https://github.com/docuracy/Locolligo/issues/9). Citation is definitely a property that WHG would want as mandatory. But it shouldn't necessarily required for the LP spec in general.

**Comment by docuracy** [comment]
https://github.com/docuracy/Locolligo/issues/9#issuecomment-1049657139
