### ISSUE TITLE
Requirement for a 'when'

### ISSUE THREAD

**Issue by docuracy** [docuracy/Locolligo#9]
PROPOSAL: drop the _requirement_ for a 'when' property to temporally scope a) an entire Feature; b) a name; c) a geometry (representative point or extent); d) a type; or e) a relation. Some datasets are temporally-agnostic.

**Comment by rsimon** [comment]
Just to chip in: I did discuss with Karl once about things which should be mandatory __for the LP spec__ vs. things that should be mandatory __for inclusion of data in WHG__. I agree that data without a `when` property isn't useful for WHG. But agree 100% that it should be a valid gazetteer record, as far as the LP spec is concerned, even without a `when`.

**Comment by docuracy** [comment]
Perhaps each use case (WHG, Peripleo, etc.) should if necessary have its own modifying JSON Schema or _flavour_ that embeds the LP standard as a sub-schema. This is what [xLP](https://github.com/docuracy/Locolligo/blob/main/schemas/xLP.json) does (although I'd like to see xLP dissolved into standard LP in due course).
